### ISSUE TITLE
Work with Ubuntu?

### ISSUE THREAD

**Issue by egedarici** [clunietp/libgmsd#1]
Hi,

Is there a way to use this library with terminal :
Command line:  gmsd.exe "path/to/file1.bmp" "path/to/file2.bmp"
like this on Ubuntu system?
Thanks.

**Comment by clunietp** [comment]
Yes, you just need to build it using cmake.

```
cmake .
cmake --build .
./gmsd "path/to/file1.bmp" "path/to/file2.bmp"
```
